server {
	listen 8085;
	listen [::]8085;

	server_name 221.121.4.31;
	
	root /var/www/devops-hackathon-de004-nguyenhuyhoan/src;
	index index.html;

	access_log /var/log/nginx/nguyenhuyhoan-k24cntt2.access.log;
	error_log /var/log/nginx/nguyenhuyhoan-k24cntt2.error.log;

	location / {
		allow all;
		try_file $uri $uri/ =404;
	}
}
